# Dockerfile para MariaDB com migrations embutidas
FROM mariadb:10.4

# Copiar scripts SQL para inicialização automática
COPY Banco_sql/clinica_encaminhamento.sql /docker-entrypoint-initdb.d/01-schema.sql
COPY Banco_sql/migration_v2.sql /docker-entrypoint-initdb.d/02-migration_v2.sql
COPY Banco_sql/migration_v3_foto.sql /docker-entrypoint-initdb.d/03-migration_v3.sql
COPY Banco_sql/migration_v4_logs.sql /docker-entrypoint-initdb.d/04-migration_v4.sql
COPY Banco_sql/migration_kanban.sql /docker-entrypoint-initdb.d/05-migration_kanban.sql
COPY Banco_sql/migration_v5_dashboard.sql /docker-entrypoint-initdb.d/06-migration_v5_dashboard.sql
COPY Banco_sql/migration_v6_procedimentos.sql /docker-entrypoint-initdb.d/07-migration_v6_procedimentos.sql
COPY Banco_sql/migration_v7_clinica_master.sql /docker-entrypoint-initdb.d/08-migration_v7_clinica_master.sql
COPY Banco_sql/migration_v8_setup.sql /docker-entrypoint-initdb.d/09-migration_v8_setup.sql
COPY Banco_sql/migration_v9_caixa.sql /docker-entrypoint-initdb.d/10-migration_v9_caixa.sql
COPY Banco_sql/migration_v10_minha_clinica.sql /docker-entrypoint-initdb.d/11-migration_v10_minha_clinica.sql
COPY Banco_sql/migration_v11_fix_guias.sql /docker-entrypoint-initdb.d/12-migration_v11_fix_guias.sql
COPY Banco_sql/migration_v12_add_dates_especialidades.sql /docker-entrypoint-initdb.d/13-migration_v12_add_dates_especialidades.sql
COPY Banco_sql/migration_v13_add_obs_clinicas.sql /docker-entrypoint-initdb.d/14-migration_v13_add_obs_clinicas.sql
COPY Banco_sql/migration_v14_imprimir_evolucao.sql /docker-entrypoint-initdb.d/15-migration_v14_imprimir_evolucao.sql
COPY Banco_sql/migration_v15_log_permission.sql /docker-entrypoint-initdb.d/16-migration_v15_log_permission.sql
COPY Banco_sql/migration_v16_prontuario_permissao.sql /docker-entrypoint-initdb.d/17-migration_v16_prontuario_permissao.sql

# Garantir permissões
RUN chmod 644 /docker-entrypoint-initdb.d/*.sql
